{ pkgs }:
let
  rustPlatformLatest = pkgs.makeRustPlatform {
    cargo = pkgs.rust-bin.stable.latest.default;
    rustc = pkgs.rust-bin.stable.latest.default;
  };
  keifu = rustPlatformLatest.buildRustPackage rec {
    pname = "keifu";
    version = "unstable-2024-12-08";
    src = pkgs.fetchFromGitHub {
      owner = "trasta298";
      repo = "keifu";
      rev = "604c04c23b47a4edcaca118eda4a60c0e6faba02";
      hash = "sha256-gqJXOV99hCtw8giU4trPAljZ8gShGp4RuB3OWXJBO3M=";
    };
    cargoPatches = [
      (pkgs.writeText "downgrade-lockfile.patch" ''
        --- a/Cargo.lock
        +++ b/Cargo.lock
        @@ -1,5 +1,5 @@
         # This file is automatically @generated by Cargo.
         # It is not intended for manual editing.
        -version = 4
        +version = 3

         [[package]]
      '')
    ];
    cargoHash = "sha256-nNgu4SpQBf6H1+C65XtBX9mNJxISi/IxaYwI2nGSbKE=";
    nativeBuildInputs = [ pkgs.pkg-config ];
    buildInputs = [ pkgs.openssl ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
      pkgs.darwin.apple_sdk.frameworks.Security
      pkgs.darwin.apple_sdk.frameworks.SystemConfiguration
    ];
    OPENSSL_NO_VENDOR = 1;
  };
  pypkgs = ps: with ps; [
    boto3
    toml
    rich
    requests
    pytest
    pynamodb
    beautifulsoup4
    daemonize
  ];
in with pkgs;
[
  binutils
  ack
  broot
  cargo
  gnumake
  jq
  k9s
  kubectl
  most
  nerdfonts
  nix-index
  nix-output-monitor
  nix-tree
  nixd
  nixdoc
  nixpkgs-fmt
  nodejs
  ripgrep
  rustc
  ssm-session-manager-plugin
  terraform
  terraform-ls
  tldr
  tree
  virtualenv
  zip
  aws-sam-cli
  awscli2
  ssm-session-manager-plugin
  # 2024 
  eza
  victor-mono
  docker-compose
  poetry
  unzip
  nix-derivation
  comma
  act
  gh
  trivy
  tmux
  keifu
  (python3.withPackages pypkgs)
]
